name: Build and Deploy Prod

on:
  push:
    branches: ["main", "beta", "develop"]

jobs:
  package_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.GITHUB_REF_NAME }}

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Yarn
        run: npm install -g yarn

      - name: Get package.json version
        id: package-version
        uses: actions/github-script@v6
        with:
          script: |
            const { getPackageVersion } = await import('${{ github.workspace }}/ci/version.js')

            const path = core.getInput('path');
            core.debug(`Load package.json at ${path}`);

            const version = getPackageVersion(path)

            core.debug(`set version: version: ${version}`);
            core.setOutput('version', version);

      - name: Checkout Badges Branch
        uses: actions/checkout@v3
        with:
          ref: badges
          token: ${{ secrets.PAT }}

      - name: Install Dependencies
        run: yarn install

      - name: Generate Badge
        uses: actions/github-script@v6
        with:
          script: |
            const { generateBadge } = await import('${{ github.workspace }}/ci/badge.js');
            const branch = '$GITHUB_REF_NAME';
            const version = '${{ steps.package-version.outputs.version }}';

            await generateBadge(branch, version);

      - name: Commit badge
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generates new version badge"
          git push
